version: "3.8"
services:
  mysql:
    image: mysql
    container_name: mysql-architecture
    ports:
      - "3306:3306"
    volumes:
      - datamysql:/var/lib/mysql
    environment:
      - MYSQL_USER=student
      - MYSQL_PASSWORD=student
      - MYSQL_ROOT_PASSWORD=student
      - MYSQL_DATABASE=moviessql
      - MYSQL_PORT=3306
      - MYSQL_HOST=localhost
  adminer:
    image: adminer
    container_name: adminer-architecture
    ports:
      - "9999:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    depends_on:
      - mysql

  mongodb:
    image: mongo
    container_name: mongodb-architecture
    ports:
      - "27017:27017"
    volumes:
      - datamongo:/var/lib/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=student
      - MONGO_INITDB_ROOT_PASSWORD=student
  mongo-express:
    image: mongo-express
    container_name: mongo-express-architecture
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=student
      - ME_CONFIG_MONGODB_ADMINPASSWORD=student
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  datamysql:
  datamongo: